GET http://localhost:8080/api/Rezept

###

GET http://localhost:8080/api/Rezept/14

###
DELETE http://localhost:8080/api/Rezept/7

###

PUT http://localhost:8080/api/Rezept/14
Content-Type: application/json
Accept: application/json

{
  "zutaten": ["Eier", "Käse"],
  "title": "Frisches Rührei",
  "beschreibung": "Platzhalter",
  "zutatVollständig": "true"
}

###

POST http://localhost:8080/api/Rezept/
Content-Type: application/json
Accept: application/json

{
  "zutaten": ["Eier", "Käse"],
  "title": "Frisches Spiegelei",
  "beschreibung": "Platzhalter",
  "zutatVollständig": "true"
}

###


