GET http://localhost:8085/api/Rezept

###

GET http://localhost:8085/api/Rezept/14

###
DELETE http://localhost:8085/api/Rezept/1

###
DELETE http://localhost:8085/api/Rezept/
###

PUT http://localhost:8085/api/Rezept/14
Content-Type: application/json
Accept: application/json

{
  "zutaten": [
    "Eier",
    "Käse"
  ],
  "title": "Frisches Rührei",
  "beschreibung": "Platzhalter",
  "zutatVollständig": "true"
}

###

POST http://localhost:8085/api/Rezept/
Content-Type: application/json
Accept: application/json

{
  "zutaten": [
    {
      "zutat": {
        "name": "Butter",
        "mdh": "2020-05-06",
        "haltbar": "false",
        "menge": {
          "einheit": "STÜCK",
          "menge": "200"
        },
        "menge": {
          "einheit": "STÜCK",
          "menge": "200"
        }
      }
    }],
      "titel": "Frisches Spiegelei",
      "beschreibung": "Platzhalter",
      "zutatVollständig": "true"

    }

###


